GET {{host}}}/room/all
Accept: application/json

###
POST {{host}}/room/list
Content-Type: application/json

{
  "pageNum": 1,
  "pageSize": 20
}

###

###
GET {{host}}/auth/createRegisterCaptcha?email=zengxpang@163.com
Accept: application/json

###
GET {{host}}/route/getUserRoute
Accept: application/json

###
GET {{host}}/app/hello
Accept: application/json
x-lang: en

###
GET {{host}}/app/name
Accept: application/json
x-lang: en

###
POST {{host}}/auth/logout
Content-Type: application/json
Authorization: Bearer {{token}}

{}

###


###
GET {{host}}/auth/userPermissions
Accept: application/json


### 生成验证码
GET {{host}}/auth/createCaptcha
Accept: application/json

### 登陆
POST {{host}}/auth/login
Content-Type: application/json
x-lang: en

{
  "username": "zengxpang",
  "password": "123456"
}

