POST {{host}}/auth/refreshToken
Content-Type: application/json
Authorization: Bearer {{refreshToken}}

{
  "refreshToken": "{{refreshToken}}"
}

###
POST {{host}}/auth/
Content-Type: application/json

{}

###
GET {{host}}/captcha/createCaptcha
Accept: application/json

###
GET {{host}}/auth/profile
Accept: application/json
Authorization: Bearer {{token}}

###
GET {{host}}/cat
Accept: application/json

###
POST {{host}}/auth/login
Content-Type: application/json

{
  "username": "sAdmin",
  "password": "sAdmin"
}

###

