### 生成验证码
GET {{host}}/auth/createCaptcha
Accept: application/json

### 登陆
POST {{host}}/auth/login
Content-Type: application/json

{
  "username": "sAdmin",
  "password": "sAdmin",
  "captcha": "1Mhe"
}

### 刷新token
POST {{host}}/auth/refreshToken
Content-Type: application/json
Authorization: Bearer {{refreshToken}}

{
  "refreshToken": "{{refreshToken}}"
}

